CREATE TABLE IF NOT EXISTS PWA_FILE_CACHE (
	ID_FILE_CACHE INTEGER PRIMARY KEY NOT NULL,
	TX_FILE TEXT NOT NULL,
	TX_HASH TEXT NOT NULL,
	VR_STATUS TEXT NOT NULL DEFAULT "active",
	DT_CREATION DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IX_PWA_FILE_CACHE_1 ON PWA_FILE_CACHE (VR_STATUS);
CREATE INDEX IF NOT EXISTS IX_PWA_FILE_CACHE_2 ON PWA_FILE_CACHE (TX_FILE, TX_HASH);
