CREATE TABLE IF NOT EXISTS TIMESLOT (
	ID_TIMESLOT INTEGER PRIMARY KEY,
	VC_SCOPE TEXT NOT NULL,
	JS_ARGS TEXT NOT NULL,
	VC_CALLBACK TEXT NOT NULL,
	VC_RETURN TEXT,
	VC_ERROR TEXT,
	DT_EXECUTION TEXT NOT NULL,
	DT_START TEXT,
	DT_END TEXT,
	DT_CREATION TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(VC_SCOPE, DT_EXECUTION)
);

CREATE INDEX IX_TIMESLOT_1 ON TIMESLOT (VC_SCOPE);
